export enum BlendType {
  Normal = 0,
  Add = 1,
  Average = 2,
  Darken = 3,
  Multiply = 4,
  ColorBurn = 5,
  LinearBurn = 6,
  Lighten = 7,
  Screen = 8,
  ColorDodge = 9,
  LinearDodge = 10,
  Overlay = 11,
  SoftLight = 12,
  HardLight = 13,
  VividLight = 14,
  LinearLight = 15,
  PinLight = 16,
  HardMix = 17,
  Difference = 18,
  Exclusion = 19,
  Subtract = 20,
  Glow = 21,
  Negation = 22,
  Phoenix = 23,
  Reflect = 24,
}
