name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Compile resume
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            ./src/resume/main.tex
          latexmk_use_xelatex: true
          extra_fonts: |
            ./src/resume/*.otf

      # The final path here should be synchronized with /content/data/resume.mdx
      - name: Move resume PDF into /public
        run: |
          mkdir -p ./public/resume
          mv ./main.pdf ./public/resume/azevedo-joseph.pdf

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true
