name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npm run build
        env:
          CI: "true"
          # Used for the resume metadata fetching via the GitHub GraphQL API
          # (needs to have `public_repo` (read-only) scope or equivalent):
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile resume
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            ./src/resume/main.tex

      # The paths here must remain synchronized with the paths in
      # content/data/resume.yaml:
      - name: Move resume PDF into /public
        run: |
          mkdir -p ./public/resume
          mv ./main.pdf ./public/resume/azevedo-joseph.pdf
      - name: Copy resume source into /public
        run: |
          cp ./src/resume/main.tex ./public/resume/main.tex

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true
